# Generated by Django 4.2.7 on 2024-10-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
